export const FILE_TYPES = {
  IMAGES: ['image/jpeg', 'image/png', 'image/gif'],
  DOCUMENTS: ['application/pdf', 'application/msword'],
  VIDEOS: ['video/mp4', 'video/mpeg'],
  AUDIO: ['audio/mp3', 'audio/mpeg'],
  ARCHIVES: ['application/zip', 'application/x-rar-compressed'],
  EXECUTABLES: ['application/x-msdownload', 'application/x-shockwave-flash'],
  TEXT: ['text/plain', 'text/csv'],
  PRESENTATIONS: [
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  ],
  SPREADSHEETS: [
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  ],
  UNKNOWN: ['application/octet-stream', 'application/x-unknown'],
  ALL: [
    'image/jpeg',
    'image/png',
    'image/gif',
    'application/pdf',
    'application/msword',
    'video/mp4',
    'video/mpeg',
    'audio/mp3',
    'audio/mpeg',
    'application/zip',
    'application/x-rar-compressed',
    'application/x-msdownload',
    'application/x-shockwave-flash',
    'text/plain',
    'text/csv',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/octet-stream',
    'application/x-unknown',
    'application/x-7z-compressed',
    'application/x-tar',
    'application/x-gzip',
    'application/x-bzip2',
    'application/x-iso9660-image',
    'application/x-dosexec',
    'application/x-shockwave-flash',
    'application/x-java-archive',
    'application/x-apple-diskimage',
  ],
};
