version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.4.0 # استخدم النسخة التي تناسبك
    working_directory: ~/project

jobs:
  build-and-test:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install Angular CLI
          command: npm install -g @angular/cli

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run unit tests
          command: npm run test -- --watch=false --browsers=ChromeHeadless

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
